version: '3'

services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # for hot reloading on Windows
    build: .
    volumes:
      - .:/code
    command: ./bin/docker-command.bash
    ports:
      - "8080:8080"
